export const START_EVENTS = new Set([
  'SOQL_EXECUTE_BEGIN',
  'DML_BEGIN',
  'CODE_UNIT_STARTED',
  'METHOD_ENTRY',
  'FLOW_START_INTERVIEW_BEGIN',
  'WF_CRITERIA_BEGIN',
  'WF_RULE_EVAL_BEGIN',
  'FLOW_CREATE_INTERVIEW_END',
  'FLOW_ELEMENT_BEGIN',
  'FLOW_BULK_ELEMENT_BEGIN',
]);

export const END_EVENTS = new Set([
  'SOQL_EXECUTE_END',
  'DML_END',
  'CODE_UNIT_FINISHED',
  'METHOD_EXIT',
  'FLOW_START_INTERVIEW_END',
  'WF_CRITERIA_END',
  'WF_RULE_EVAL_END',
  'WF_RULE_NOT_EVALUATED',
  'FLOW_INTERVIEW_FINISHED',
  'FLOW_ELEMENT_END',
  'FLOW_BULK_ELEMENT_END',
]);

export const WORKFLOW_EVENTS = new Set([
  'WF_CRITERIA_BEGIN',
  'WF_CRITERIA_END',
  'FLOW_START_INTERVIEW_BEGIN',
  'FLOW_START_INTERVIEW_END',
  'WF_RULE_EVAL_BEGIN',
  'WF_RULE_EVAL_END',
  'WF_RULE_NOT_EVALUATED',
  'FLOW_CREATE_INTERVIEW_END',
  'FLOW_INTERVIEW_FINISHED',
  'FLOW_ELEMENT_BEGIN',
  'FLOW_ELEMENT_END',
  'FLOW_BULK_ELEMENT_BEGIN',
  'FLOW_BULK_ELEMENT_END',
]);

export function isFlowLimitUsageEvent(event: string): boolean {
  return (
    event === 'FLOW_ELEMENT_LIMIT_USAGE' ||
    event === 'FLOW_BULK_ELEMENT_LIMIT_USAGE'
  );
}
